version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dreamcakes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3307:3306'

  cake_app:
    image: ilhaamm/filrouge:latest
    ports:
      - '8089:8089'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/dreamcakes
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql-db

